(function(root){
  'use strict';
  const species = {
    spriglet:{name:'Spriglet',type:'Grove',color:'#79a85a',accent:'#d7dc83',shape:'fox',hp:32,attack:10,defense:8,skill:'Bramble burst',evolve:'thornhart',description:'A curious woodland spirit. The leaves on its ears turn toward the sun.'},
    cindercub:{name:'Cindercub',type:'Ember',color:'#d1814e',accent:'#f3cc74',shape:'cat',hp:30,attack:12,defense:6,skill:'Cinder rush',evolve:'pyrolynx',description:'Keeps a tiny coal beneath its mane. It purrs like a crackling campfire.'},
    ripplefin:{name:'Ripplefin',type:'Tide',color:'#6ba9ba',accent:'#c3e5d7',shape:'fin',hp:35,attack:9,defense:9,skill:'Tidal pulse',evolve:'tideray',description:'A little river guardian that swims through both water and mist.'},
    mothglow:{name:'Mothglow',type:'Grove',color:'#b5b474',accent:'#e8e4ad',shape:'moth',hp:26,attack:11,defense:6,skill:'Pollen flare',description:'Its glowing wings once guided travelers through the dark forest.'},
    pebblit:{name:'Pebblit',type:'Stone',color:'#9c9d8b',accent:'#ced3bb',shape:'rock',hp:38,attack:9,defense:12,skill:'Boulder roll',description:'Collects smooth stones and carries its favorite one wherever it goes.'},
    reedle:{name:'Reedle',type:'Tide',color:'#7daca0',accent:'#d6d788',shape:'frog',hp:33,attack:10,defense:8,skill:'Reed surge',description:'The reeds on its head whistle before the rain arrives.'},
    voltkit:{name:'Voltkit',type:'Spark',color:'#dbc86e',accent:'#fff0b4',shape:'fox',hp:29,attack:13,defense:6,skill:'Static leap',description:'A restless companion whose fur glimmers before a thunderstorm.'},
    duskowl:{name:'Duskowl',type:'Stone',color:'#9c91ab',accent:'#d5cce0',shape:'owl',hp:34,attack:12,defense:9,skill:'Moonstone fall',description:'Sleeps in ancient ruins. Its eyes remember the light of the old beacon.'},
    solwyrm:{name:'Solwyrm',type:'Ember',color:'#d6aa69',accent:'#f8e8ab',shape:'dragon',hp:42,attack:14,defense:10,skill:'Solar breath',description:'The last keeper of the beacon. Its flame grows brighter around friends.'},
    glimmerbat:{name:'Glimmerbat',type:'Stone',color:'#7f83a5',accent:'#d9d3ef',shape:'moth',hp:31,attack:13,defense:8,skill:'Crystal echo',description:'Its wings sing against cave walls, revealing paths hidden in darkness.'},
    coralisk:{name:'Coralisk',type:'Tide',color:'#df8d7a',accent:'#bce4dc',shape:'fin',hp:39,attack:12,defense:11,skill:'Reef rush',description:'A bright coastal guardian that builds tiny reefs wherever it rests.'},
    mossboar:{name:'Mossboar',type:'Grove',color:'#667f55',accent:'#b5c77e',shape:'rock',hp:46,attack:13,defense:13,skill:'Ancient root',description:'Old trail-moss grows across its patient back like a moving hill.'},
    stormjay:{name:'Stormjay',type:'Spark',color:'#657fa2',accent:'#f0db72',shape:'owl',hp:33,attack:15,defense:7,skill:'Thunder cry',description:'It gathers the charge of distant storms in its sharp blue feathers.'},
    emberwing:{name:'Emberwing',type:'Ember',color:'#b65f55',accent:'#f3c96d',shape:'moth',hp:32,attack:15,defense:7,skill:'Lantern blaze',description:'Ruined lanterns flicker to life when this warm-winged spirit passes.'},
    mireling:{name:'Mireling',type:'Tide',color:'#658f79',accent:'#cee09c',shape:'frog',hp:41,attack:11,defense:12,skill:'Bog chorus',description:'A shy cave-dweller whose song makes underground pools ripple.'},
    thornhart:{name:'Thornhart',type:'Grove',color:'#518963',accent:'#c1d788',shape:'stag',hp:45,attack:15,defense:12,skill:'Verdant storm',description:'Spriglet, awakened. Its antlers shelter an entire miniature garden.'},
    pyrolynx:{name:'Pyrolynx',type:'Ember',color:'#c97348',accent:'#ffe4a0',shape:'cat',hp:43,attack:17,defense:10,skill:'Blazing comet',description:'Cindercub, awakened. Its footprints leave warm sparks on cold stone.'},
    tideray:{name:'Tideray',type:'Tide',color:'#589eac',accent:'#d1f1e6',shape:'fin',hp:48,attack:14,defense:13,skill:'Ocean song',description:'Ripplefin, awakened. A single song can calm a raging river.'}
  };
  const areas = {
    glen:{name:'Briar Glen',subtitle:'A place to begin',flavor:'HOME, FOR NOW.',palette:['#88a565','#79995e','#627f4c'],wild:['spriglet','cindercub','ripplefin','mothglow','pebblit'],levels:[2,4],npcs:[{id:'guide',x:13,y:12,name:'Ranger Elowen',role:'guide'}],exits:[{x:27,y:8,to:'fen',tx:1,ty:8},{x:13,y:0,to:'whisperwood',tx:13,ty:16},{x:7,y:7,to:'resthouse',tx:14,ty:15},{x:20,y:7,to:'market',tx:14,ty:15}]},
    fen:{name:'Mosswater Fen',subtitle:'Where the river remembers',flavor:'FOLLOW THE FIREFLIES.',palette:['#799970','#6c8d67','#53795f'],wild:['reedle','mothglow','voltkit','ripplefin'],levels:[4,7],npcs:[{id:'fenhealer',x:5,y:8,name:'Traveling herbalist',role:'healer'},{id:'warden1',x:21,y:8,name:'Warden Sable',role:'warden',badge:'reed',team:[['reedle',5],['mothglow',6]]}],exits:[{x:0,y:8,to:'glen',tx:26,ty:8},{x:27,y:8,to:'verdantpass',tx:1,ty:8,requires:'reed'}]},
    verdantpass:{name:'Verdant Pass',subtitle:'A switchback road beneath giant roots',flavor:'THE LONG ROAD BEGINS.',palette:['#71905d','#648455','#4e704d'],wild:['spriglet','mossboar','mothglow','voltkit'],levels:[6,9],route:1,npcs:[{id:'passguide',x:11,y:8,name:'Scout Rowan',role:'ranger'},{id:'cache1',x:25,y:4,name:'Mossbound satchel',role:'cache',reward:{coins:20,orbs:2,potions:0}}],exits:[{x:0,y:8,to:'fen',tx:26,ty:8},{x:27,y:8,to:'stormmarsh',tx:1,ty:8}]},
    stormmarsh:{name:'Stormglass Marsh',subtitle:'A crooked boardwalk over thunderwater',flavor:'STEP WHERE THE REEDS BEND.',palette:['#587b70','#4d6e68','#3c5d5d'],wild:['reedle','voltkit','stormjay','mireling'],levels:[7,11],route:2,npcs:[{id:'marshcamp',x:6,y:8,name:'Storm camp',role:'healer'},{id:'warden_tide',x:21,y:8,name:'Warden Neris',role:'warden',badge:'tide',team:[['reedle',9],['coralisk',10]]},{id:'cache2',x:11,y:12,name:'Drowned supply crate',role:'cache',reward:{coins:30,orbs:1,potions:1}}],exits:[{x:0,y:8,to:'verdantpass',tx:26,ty:8},{x:27,y:8,to:'emberbasin',tx:1,ty:8,requires:'tide'}]},
    emberbasin:{name:'Ember Basin',subtitle:'A climbing trail around rivers of fire',flavor:'ASH FALLS LIKE SNOW.',palette:['#9a7050','#885f48','#6e4d43'],wild:['cindercub','emberwing','pebblit','glimmerbat'],levels:[9,13],route:3,npcs:[{id:'basincamp',x:6,y:8,name:'Ash camp',role:'healer'},{id:'warden_ember',x:21,y:8,name:'Warden Kael',role:'warden',badge:'ember',team:[['emberwing',11],['cindercub',12],['pebblit',11]]},{id:'cache3',x:10,y:5,name:'Ashforged chest',role:'cache',reward:{coins:35,orbs:2,potions:1}}],exits:[{x:0,y:8,to:'stormmarsh',tx:26,ty:8},{x:27,y:8,to:'frosthollow',tx:1,ty:8,requires:'ember'}]},
    frosthollow:{name:'Frost Hollow',subtitle:'A frozen switchback beneath an ice arch',flavor:'KEEP THE FIRE CLOSE.',palette:['#8da9a5','#789995','#637f83'],wild:['glimmerbat','stormjay','ripplefin','duskowl'],levels:[10,14],route:4,npcs:[{id:'frostkeeper',x:7,y:11,name:'Hearthkeeper Una',role:'healer'},{id:'frostguide',x:19,y:8,name:'Climber Tor',role:'ranger'},{id:'cache4',x:16,y:4,name:'Frozen ranger pack',role:'cache',reward:{coins:25,orbs:1,potions:2}}],exits:[{x:0,y:8,to:'emberbasin',tx:26,ty:8},{x:27,y:8,to:'shardmaze',tx:1,ty:8}]},
    shardmaze:{name:'The Shardmaze',subtitle:'A glittering labyrinth with false turns',flavor:'REFLECTIONS CAN LIE.',palette:['#756e87','#68627b','#514f69'],wild:['glimmerbat','duskowl','mireling','voltkit'],levels:[11,15],route:5,npcs:[{id:'mazeguide',x:13,y:5,name:'Cartographer Pell',role:'ranger'},{id:'cache5',x:7,y:4,name:'Prism cache',role:'cache',reward:{coins:45,orbs:2,potions:1}}],exits:[{x:0,y:8,to:'frosthollow',tx:26,ty:8},{x:27,y:8,to:'ancientgarden',tx:1,ty:8}]},
    ancientgarden:{name:'Ancient Garden',subtitle:'A ruined city wrapped in living roots',flavor:'GROWTH OUTLASTS STONE.',palette:['#657d55','#58714f','#465d47'],wild:['mossboar','spriglet','mothglow','duskowl'],levels:[12,16],route:6,npcs:[{id:'gardenboard',x:8,y:6,name:'Garden expedition board',role:'guild'},{id:'gardener',x:20,y:8,name:'Keeper Moss',role:'ranger'},{id:'cache6',x:16,y:11,name:'Rootbound reliquary',role:'cache',reward:{coins:40,orbs:3,potions:0}}],exits:[{x:0,y:8,to:'shardmaze',tx:26,ty:8},{x:27,y:8,to:'sunkensanctum',tx:1,ty:8}]},
    sunkensanctum:{name:'Sunken Sanctum',subtitle:'Temple causeways beneath the inland sea',flavor:'BREATHE WITH THE TIDE.',palette:['#4d7776','#426c70','#365b66'],wild:['coralisk','mireling','ripplefin','reedle'],levels:[13,17],route:7,npcs:[{id:'sanctumcamp',x:7,y:8,name:'Diver’s refuge',role:'healer'},{id:'diver',x:19,y:13,name:'Diver Sio',role:'ranger'},{id:'cache7',x:10,y:4,name:'Tideworn coffer',role:'cache',reward:{coins:35,orbs:2,potions:2}}],exits:[{x:0,y:8,to:'ancientgarden',tx:26,ty:8},{x:27,y:8,to:'cloudstep',tx:1,ty:8}]},
    cloudstep:{name:'Cloudstep Isles',subtitle:'Narrow skybridges between floating stones',flavor:'THE SKY HAS PATHS TOO.',palette:['#93a6a0','#829692','#6e817f'],wild:['stormjay','duskowl','emberwing','voltkit'],levels:[14,18],route:8,npcs:[{id:'skyhealer',x:7,y:8,name:'Wind shelter',role:'healer'},{id:'pilot',x:18,y:8,name:'Glider Iri',role:'ranger'},{id:'cache8',x:11,y:11,name:'Lost glider crate',role:'cache',reward:{coins:50,orbs:2,potions:1}}],exits:[{x:0,y:8,to:'sunkensanctum',tx:26,ty:8},{x:27,y:8,to:'starbridge',tx:1,ty:8}]},
    starbridge:{name:'Starbridge',subtitle:'A constellation road above the dark',flavor:'ONLY COURAGE CROSSES.',palette:['#666c84','#595f77','#454c66'],wild:['stormjay','glimmerbat','duskowl','emberwing'],levels:[15,19],route:9,npcs:[{id:'warden_sky',x:21,y:8,name:'Warden Lyra',role:'warden',badge:'sky',team:[['stormjay',17],['duskowl',18],['glimmerbat',17]]},{id:'cache9',x:9,y:4,name:'Fallen-star cache',role:'cache',reward:{coins:55,orbs:2,potions:2}}],exits:[{x:0,y:8,to:'cloudstep',tx:26,ty:8},{x:27,y:8,to:'aurorapeak',tx:1,ty:8,requires:'sky'}]},
    aurorapeak:{name:'Aurora Peak',subtitle:'A spiral ascent through curtains of light',flavor:'THE BEACON IS NEAR.',palette:['#84938c','#74847f','#606f6e'],wild:['stormjay','solwyrm','glimmerbat','mossboar'],levels:[17,21],route:10,npcs:[{id:'aurorahealer',x:6,y:8,name:'Last-light camp',role:'healer'},{id:'pilgrim',x:19,y:8,name:'Pilgrim Vey',role:'ranger'},{id:'cache10',x:16,y:11,name:'Pilgrim’s offering',role:'cache',reward:{coins:60,orbs:3,potions:2}}],exits:[{x:0,y:8,to:'starbridge',tx:26,ty:8},{x:27,y:8,to:'summit',tx:1,ty:8}]},
    summit:{name:'Starfall Ridge',subtitle:'At the edge of the sky',flavor:'THE OLD LIGHT WAITS.',palette:['#9aa08a','#8c957d','#7c8872'],wild:['pebblit','voltkit','duskowl','cindercub','stormjay'],levels:[18,22],npcs:[{id:'ridgehealer',x:5,y:8,name:'Beacon keeper',role:'healer'},{id:'warden2',x:15,y:8,name:'Warden Orin',role:'warden',badge:'stone',team:[['pebblit',19],['voltkit',20],['duskowl',19]]},{id:'beacon',x:23,y:5,name:'The sleeping beacon',role:'boss'}],exits:[{x:0,y:8,to:'aurorapeak',tx:26,ty:8},{x:24,y:4,to:'beaconhall',tx:14,ty:15,requires:'stone'}]},
    whisperwood:{name:'Whisperwood',subtitle:'A forest that changes its mind',flavor:'LISTEN BETWEEN THE LEAVES.',palette:['#537b55','#476d4d','#355b44'],wild:['spriglet','mothglow','mossboar','stormjay','glimmerbat'],levels:[5,9],npcs:[{id:'woodranger',x:9,y:8,name:'Ranger Fenn',role:'ranger'},{id:'woodboard',x:18,y:8,name:'Trail bounty board',role:'guild'}],exits:[{x:13,y:17,to:'glen',tx:13,ty:1},{x:0,y:8,to:'sunshore',tx:26,ty:8},{x:27,y:8,to:'moonruins',tx:1,ty:8,requires:'stone'}]},
    sunshore:{name:'Sunshore Coast',subtitle:'Salt, wind and hidden coves',flavor:'THE TIDE KEEPS SECRETS.',palette:['#92aa72','#829d67','#6e8b5c'],wild:['ripplefin','reedle','coralisk','emberwing'],levels:[6,10],npcs:[{id:'coasthealer',x:7,y:8,name:'Shore camp',role:'healer'},{id:'fisher',x:13,y:11,name:'Old Maren',role:'ranger'}],exits:[{x:27,y:8,to:'whisperwood',tx:1,ty:8}]},
    moonruins:{name:'Moonveil Ruins',subtitle:'Broken halls beneath the stars',flavor:'EVERY STONE REMEMBERS.',palette:['#777a70','#686d66','#555f5b'],wild:['duskowl','glimmerbat','emberwing','voltkit'],levels:[8,12],npcs:[{id:'ruinkeeper',x:8,y:9,name:'Archivist Nymm',role:'ranger'},{id:'ruinboard',x:19,y:9,name:'Ancient contract stone',role:'guild'}],exits:[{x:0,y:8,to:'whisperwood',tx:26,ty:8},{x:14,y:0,to:'crystaldepths',tx:14,ty:16}]},
    crystaldepths:{name:'Crystal Depths',subtitle:'The luminous world below',flavor:'LIGHT GROWS IN THE DARK.',palette:['#506d68','#46615e','#384e51'],wild:['glimmerbat','mireling','pebblit','coralisk'],levels:[10,14],npcs:[{id:'deephealer',x:6,y:9,name:'Cavern camp',role:'healer'},{id:'deepwarden',x:21,y:7,name:'Delver Iona',role:'ranger'}],exits:[{x:14,y:17,to:'moonruins',tx:14,ty:1}]},
    resthouse:{name:'Mira’s Rest House',subtitle:'Warm beds and familiar stories',flavor:'COME IN FROM THE WILD.',palette:['#b7a879','#a79770','#897f63'],wild:[],levels:[1,1],indoor:true,npcs:[{id:'mira',x:11,y:8,name:'Mira · Healing',role:'healer'},{id:'steward',x:17,y:8,name:'Nell · Sanctuary steward',role:'caretaker'}],exits:[{x:14,y:16,to:'glen',tx:7,ty:8}]},
    market:{name:'Tavi’s Trail Market',subtitle:'Useful things for difficult roads',flavor:'PACK FOR THE LONG WAY.',palette:['#b8a476','#a08c65','#806f54'],wild:[],levels:[1,1],indoor:true,npcs:[{id:'tavi',x:13,y:7,name:'Tavi · Trail supplies',role:'shop'},{id:'broker',x:18,y:7,name:'Bex · Expedition broker',role:'guild'}],exits:[{x:14,y:16,to:'glen',tx:20,ty:8}]},
    beaconhall:{name:'Beacon Hall',subtitle:'The chamber behind the light',flavor:'OLD FIRE, NEW PATHS.',palette:['#98977e','#858673','#6c776d'],wild:[],levels:[1,1],indoor:true,npcs:[{id:'hallkeeper',x:10,y:8,name:'Keeper Asha',role:'healer'},{id:'beaconarchive',x:18,y:8,name:'Beacon archive',role:'guild'}],exits:[{x:14,y:16,to:'summit',tx:24,ty:5}]}
  };
  Object.assign(species,{
    rootling:{name:'Rootling',type:'Grove',color:'#668b54',accent:'#d8d08a',shape:'rock',hp:37,attack:10,defense:13,skill:'Root snare',description:'A patient burrow spirit that knots old roots into protective armor.'},
    sporekin:{name:'Sporekin',type:'Venom',color:'#8e7197',accent:'#d6c18a',shape:'frog',hp:34,attack:13,defense:8,skill:'Dream spores',description:'Its cap releases sparkling spores that make predators forget the chase.'},
    frostling:{name:'Frostling',type:'Frost',color:'#82aeba',accent:'#e4f2e8',shape:'fox',hp:33,attack:13,defense:9,skill:'Rime veil',description:'A playful spirit born where winter streams first touch stone.'},
    luminox:{name:'Luminox',type:'Light',color:'#d2b869',accent:'#fff0ae',shape:'stag',hp:43,attack:14,defense:11,skill:'Dawn chorus',description:'Its lantern antlers reveal paths hidden by fear and shadow.'},
    gearmite:{name:'Gearmite',type:'Metal',color:'#7f8f91',accent:'#d8c67b',shape:'rock',hp:40,attack:12,defense:15,skill:'Copper guard',description:'A tiny vault keeper assembled by the vanished craftspeople of the Vale.'},
    gloomfang:{name:'Gloomfang',type:'Shadow',color:'#544d67',accent:'#be91aa',shape:'cat',hp:48,attack:16,defense:11,skill:'Night pounce',description:'A wary guardian that learned to survive alone beneath Hollowroot Well.'},
    rootwarden:{name:'Rootwarden',type:'Spirit',color:'#54745c',accent:'#e3c878',shape:'stag',hp:58,attack:17,defense:14,skill:'Heartwood oath',description:'An ancient protector awakened by the broken song beneath Briar Glen.'}
  });
  areas.glen.wild.push('rootling');
  areas.glen.npcs.push({id:'notice',x:3,y:12,name:'Hollowroot notice',role:'landmark'});
  areas.glen.exits.push(
    {x:13,y:7,to:'lodge',tx:14,ty:15},
    {x:24,y:12,to:'farmhouse',tx:14,ty:15},
    {x:3,y:14,to:'oldwell',tx:14,ty:16}
  );
  Object.assign(areas,{
    lodge:{name:'Pathfinder Lodge',subtitle:'Maps, rumors and ranger contracts',flavor:'EVERY JOURNEY LEAVES A MARK.',palette:['#ad9b6f','#97855f','#74654e'],wild:[],levels:[1,1],indoor:true,npcs:[{id:'mara',x:10,y:8,name:'Captain Mara',role:'questgiver',quests:['field_notes','battle_ready','secret_keeper','well_whispers']},{id:'venn',x:18,y:8,name:'Scholar Venn',role:'questgiver',quests:['village_helper','root_of_trouble','glen_mastery']},{id:'lodgeboard',x:14,y:5,name:'Pathfinder contract board',role:'guild'}],exits:[{x:14,y:16,to:'glen',tx:13,ty:8}]},
    farmhouse:{name:'Moonleaf Farm',subtitle:'A bright kitchen at the edge of town',flavor:'SMALL REMEDIES, GREAT COURAGE.',palette:['#b9a474','#a18d65','#7f704f'],wild:[],levels:[1,1],indoor:true,npcs:[{id:'nia',x:11,y:8,name:'Herbalist Nia',role:'questgiver',quests:['herbal_remedy','lost_charm']},{id:'orrin',x:18,y:8,name:'Farmer Orrin',role:'ranger'}],exits:[{x:14,y:16,to:'glen',tx:24,ty:13}]},
    oldwell:{name:'Hollowroot Well',subtitle:'A flooded maze beneath Briar Glen',flavor:'THE ROOTS REMEMBER.',palette:['#435b52','#384e49','#2c403d'],wild:['sporekin','rootling','glimmerbat','mireling'],levels:[5,9],dungeon:true,npcs:[{id:'toma',x:5,y:5,name:'Explorer Toma',role:'questgiver',quests:['missing_delver']},{id:'wellcache',x:7,y:14,name:'Flooded reliquary',role:'cache',reward:{coins:45,orbs:2,potions:2,item:'echocharm'}},{id:'gloomfang',x:22,y:3,name:'Gloomfang, Well Stalker',role:'miniboss',team:[['sporekin',7],['gloomfang',9]]}],exits:[{x:14,y:17,to:'glen',tx:3,ty:13},{x:27,y:3,to:'rootvault',tx:1,ty:8,requiresClaim:'defeated-gloomfang'}]},
    rootvault:{name:'Rootbound Vault',subtitle:'The heart chamber below the village',flavor:'AN OLD OATH STIRS.',palette:['#3d594d','#324a43','#273c38'],wild:['rootling','sporekin','gearmite'],levels:[7,10],dungeon:true,npcs:[{id:'rootwarden',x:21,y:8,name:'The Rootwarden',role:'regionalboss',team:[['gearmite',9],['rootwarden',12]]},{id:'vaultcache',x:17,y:4,name:'Heartwood treasury',role:'cache',reward:{coins:90,orbs:4,potions:3,item:'prismdust'}}],exits:[{x:0,y:8,to:'oldwell',tx:26,ty:3}]}
  });
  const abilities={
    'Bramble burst':{type:'Grove',power:15,effect:'snare',description:'Roots lower the foe’s next attack.'},'Cinder rush':{type:'Ember',power:17,effect:'burn',description:'May leave a lingering burn.'},'Tidal pulse':{type:'Tide',power:14,effect:'heal',description:'Restores a little health on impact.'},'Pollen flare':{type:'Grove',power:14,effect:'weaken',description:'Softens the foe’s defenses.'},'Boulder roll':{type:'Stone',power:16,effect:'stun',description:'May briefly stun the foe.'},'Reed surge':{type:'Tide',power:14,effect:'heal',description:'Restores health with cool water.'},'Static leap':{type:'Spark',power:18,effect:'stun',description:'May interrupt the foe.'},'Moonstone fall':{type:'Stone',power:17,effect:'weaken',description:'Cracks through defenses.'},'Solar breath':{type:'Ember',power:20,effect:'burn',description:'Scorches the battlefield.'},'Crystal echo':{type:'Stone',power:16,effect:'focus',description:'Echoes restore one focus.'},'Reef rush':{type:'Tide',power:17,effect:'shield',description:'Raises a coral guard.'},'Ancient root':{type:'Grove',power:16,effect:'shield',description:'Grows a protective barrier.'},'Thunder cry':{type:'Spark',power:19,effect:'stun',description:'May silence the foe’s turn.'},'Lantern blaze':{type:'Ember',power:18,effect:'burn',description:'Leaves bright embers behind.'},'Bog chorus':{type:'Tide',power:15,effect:'weaken',description:'A disorienting underground song.'},'Verdant storm':{type:'Grove',power:21,effect:'heal',description:'Restores health as leaves spiral.'},'Blazing comet':{type:'Ember',power:22,effect:'burn',description:'A fierce strike with lasting flame.'},'Ocean song':{type:'Tide',power:20,effect:'shield',description:'A wave shields the whole team.'},'Root snare':{type:'Grove',power:15,effect:'snare',description:'Entangles and weakens the next hit.'},'Dream spores':{type:'Venom',power:17,effect:'poison',description:'Inflicts damage over time.'},'Rime veil':{type:'Frost',power:16,effect:'shield',description:'Wraps the user in protective frost.'},'Dawn chorus':{type:'Light',power:19,effect:'heal',description:'A hopeful song restores health.'},'Copper guard':{type:'Metal',power:16,effect:'shield',description:'Raises a sturdy plated guard.'},'Night pounce':{type:'Shadow',power:20,effect:'weaken',description:'Exposes the foe to the next attack.'},'Heartwood oath':{type:'Spirit',power:22,effect:'heal',description:'Ancient roots mend their guardian.'}
  };
  const items={
    bindstone:{name:'Bindstone',category:'Capture',rarity:'Common',description:'Befriends a weakened wild creature.'},tonic:{name:'Trail Tonic',category:'Consumable',rarity:'Common',description:'Restores 40 HP.'},moonleaf:{name:'Moonleaf',category:'Material',rarity:'Common',description:'A cool herb used by Briar Glen healers.'},ironroot:{name:'Ironroot',category:'Material',rarity:'Uncommon',description:'A dense root that rings like metal.'},echocharm:{name:'Echo Charm',category:'Key item',rarity:'Rare',description:'Toma’s charm, recovered from the flooded well.'},prismdust:{name:'Prism Dust',category:'Material',rarity:'Rare',description:'Light shed by an awakened ancient guardian.'},emberseed:{name:'Emberseed',category:'Material',rarity:'Uncommon',description:'A warm seed found near volcanic trails.'},tideshell:{name:'Tideshell',category:'Material',rarity:'Uncommon',description:'A shell patterned with moving currents.'},stormglass:{name:'Stormglass',category:'Material',rarity:'Rare',description:'A crystal charged by distant thunder.'},frostbloom:{name:'Frostbloom',category:'Material',rarity:'Rare',description:'A flower that opens only on ice.'},mosswrap:{name:'Moss Wrap',category:'Consumable',rarity:'Common',description:'A field dressing woven from soft moss.'},focusberry:{name:'Focus Berry',category:'Consumable',rarity:'Uncommon',description:'Restores battle focus.'},pathfinderpin:{name:'Pathfinder Pin',category:'Equipment',rarity:'Rare',description:'Awarded for helping the starting region.'},vaultkey:{name:'Rootbound Key',category:'Key item',rarity:'Rare',description:'Opens the heart chamber below Hollowroot Well.'},starfragment:{name:'Star Fragment',category:'Material',rarity:'Epic',description:'A fragment humming with beacon light.'}
  };
  const quests={
    first_steps:{title:'First Steps',giver:'Ranger Elowen',description:'Speak with Elowen and take the ranger supplies.',objective:{kind:'claimed',target:'elowen',amount:1},reward:{coins:20,item:'moonleaf',amount:1}},
    field_notes:{title:'Field Notes',giver:'Captain Mara',description:'Discover 5 different creature species.',objective:{kind:'caught',amount:5},reward:{coins:55,orbs:3}},
    herbal_remedy:{title:'A Herbal Remedy',giver:'Herbalist Nia',description:'Gather 3 Moonleaf from battles in Briar Glen and Hollowroot Well.',objective:{kind:'item',target:'moonleaf',amount:3},reward:{coins:45,potions:3}},
    missing_delver:{title:'The Missing Delver',giver:'Explorer Toma',description:'Find Explorer Toma inside Hollowroot Well.',objective:{kind:'area',target:'oldwell',amount:1},reward:{coins:35,item:'ironroot',amount:2}},
    well_whispers:{title:'Whispers in the Well',giver:'Captain Mara',description:'Defeat Gloomfang at the deepest fork of Hollowroot Well.',objective:{kind:'claimed',target:'defeated-gloomfang',amount:1},reward:{coins:80,orbs:4}},
    root_of_trouble:{title:'Root of the Trouble',giver:'Scholar Venn',description:'Defeat the Rootwarden in the Rootbound Vault.',objective:{kind:'claimed',target:'defeated-rootwarden',amount:1},reward:{coins:120,item:'pathfinderpin',amount:1}},
    secret_keeper:{title:'Secret Keeper',giver:'Captain Mara',description:'Open 3 hidden caches anywhere in the Vale.',objective:{kind:'caches',amount:3},reward:{coins:70,potions:2}},
    battle_ready:{title:'Battle Ready',giver:'Captain Mara',description:'Win 8 battles.',objective:{kind:'wins',amount:8},reward:{coins:65,orbs:2}},
    village_helper:{title:'Neighbors of the Glen',giver:'Scholar Venn',description:'Visit the Rest House, Market, Lodge and Moonleaf Farm.',objective:{kind:'areas',targets:['resthouse','market','lodge','farmhouse'],amount:4},reward:{coins:60,item:'moonleaf',amount:2}},
    lost_charm:{title:'The Lost Echo Charm',giver:'Herbalist Nia',description:'Recover the Echo Charm from the flooded reliquary.',objective:{kind:'item',target:'echocharm',amount:1},reward:{coins:75,potions:4}},
    glen_mastery:{title:'Briar Glen Pathfinder',giver:'Scholar Venn',description:'Finish the well adventure and discover 8 species.',objective:{kind:'mastery',amount:8},reward:{coins:150,item:'starfragment',amount:1}}
  };
  const advantages={Grove:'Tide',Tide:'Ember',Ember:'Grove',Stone:'Spark',Spark:'Tide',Venom:'Grove',Frost:'Grove',Light:'Shadow',Shadow:'Spirit',Spirit:'Metal',Metal:'Frost'};
  const api={species,areas,abilities,items,quests,advantages,starters:['spriglet','cindercub','ripplefin'],SAVE_KEY:'emberwild-save-v1'};
  root.EWData=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
