(function(root){
  'use strict';
  const species = {
    spriglet:{name:'Spriglet',type:'Grove',color:'#79a85a',accent:'#d7dc83',shape:'fox',hp:32,attack:10,defense:8,skill:'Bramble burst',evolve:'thornhart',description:'A curious woodland spirit. The leaves on its ears turn toward the sun.'},
    cindercub:{name:'Cindercub',type:'Ember',color:'#d1814e',accent:'#f3cc74',shape:'cat',hp:30,attack:12,defense:6,skill:'Cinder rush',evolve:'pyrolynx',description:'Keeps a tiny coal beneath its mane. It purrs like a crackling campfire.'},
    ripplefin:{name:'Ripplefin',type:'Tide',color:'#6ba9ba',accent:'#c3e5d7',shape:'fin',hp:35,attack:9,defense:9,skill:'Tidal pulse',evolve:'tideray',description:'A little river guardian that swims through both water and mist.'},
    mothglow:{name:'Mothglow',type:'Grove',color:'#b5b474',accent:'#e8e4ad',shape:'moth',hp:26,attack:11,defense:6,skill:'Pollen flare',description:'Its glowing wings once guided travelers through the dark forest.'},
    pebblit:{name:'Pebblit',type:'Stone',color:'#9c9d8b',accent:'#ced3bb',shape:'rock',hp:38,attack:9,defense:12,skill:'Boulder roll',description:'Collects smooth stones and carries its favorite one wherever it goes.'},
    reedle:{name:'Reedle',type:'Tide',color:'#7daca0',accent:'#d6d788',shape:'frog',hp:33,attack:10,defense:8,skill:'Reed surge',description:'The reeds on its head whistle before the rain arrives.'},
    voltkit:{name:'Voltkit',type:'Spark',color:'#dbc86e',accent:'#fff0b4',shape:'fox',hp:29,attack:13,defense:6,skill:'Static leap',description:'A restless companion whose fur glimmers before a thunderstorm.'},
    duskowl:{name:'Duskowl',type:'Stone',color:'#9c91ab',accent:'#d5cce0',shape:'owl',hp:34,attack:12,defense:9,skill:'Moonstone fall',description:'Sleeps in ancient ruins. Its eyes remember the light of the old beacon.'},
    solwyrm:{name:'Solwyrm',type:'Ember',color:'#d6aa69',accent:'#f8e8ab',shape:'dragon',hp:42,attack:14,defense:10,skill:'Solar breath',description:'The last keeper of the beacon. Its flame grows brighter around friends.'},
    glimmerbat:{name:'Glimmerbat',type:'Stone',color:'#7f83a5',accent:'#d9d3ef',shape:'moth',hp:31,attack:13,defense:8,skill:'Crystal echo',description:'Its wings sing against cave walls, revealing paths hidden in darkness.'},
    coralisk:{name:'Coralisk',type:'Tide',color:'#df8d7a',accent:'#bce4dc',shape:'fin',hp:39,attack:12,defense:11,skill:'Reef rush',description:'A bright coastal guardian that builds tiny reefs wherever it rests.'},
    mossboar:{name:'Mossboar',type:'Grove',color:'#667f55',accent:'#b5c77e',shape:'rock',hp:46,attack:13,defense:13,skill:'Ancient root',description:'Old trail-moss grows across its patient back like a moving hill.'},
    stormjay:{name:'Stormjay',type:'Spark',color:'#657fa2',accent:'#f0db72',shape:'owl',hp:33,attack:15,defense:7,skill:'Thunder cry',description:'It gathers the charge of distant storms in its sharp blue feathers.'},
    emberwing:{name:'Emberwing',type:'Ember',color:'#b65f55',accent:'#f3c96d',shape:'moth',hp:32,attack:15,defense:7,skill:'Lantern blaze',description:'Ruined lanterns flicker to life when this warm-winged spirit passes.'},
    mireling:{name:'Mireling',type:'Tide',color:'#658f79',accent:'#cee09c',shape:'frog',hp:41,attack:11,defense:12,skill:'Bog chorus',description:'A shy cave-dweller whose song makes underground pools ripple.'},
    thornhart:{name:'Thornhart',type:'Grove',color:'#518963',accent:'#c1d788',shape:'stag',hp:45,attack:15,defense:12,skill:'Verdant storm',description:'Spriglet, awakened. Its antlers shelter an entire miniature garden.'},
    pyrolynx:{name:'Pyrolynx',type:'Ember',color:'#c97348',accent:'#ffe4a0',shape:'cat',hp:43,attack:17,defense:10,skill:'Blazing comet',description:'Cindercub, awakened. Its footprints leave warm sparks on cold stone.'},
    tideray:{name:'Tideray',type:'Tide',color:'#589eac',accent:'#d1f1e6',shape:'fin',hp:48,attack:14,defense:13,skill:'Ocean song',description:'Ripplefin, awakened. A single song can calm a raging river.'}
  };
  const areas = {
    glen:{name:'Briar Glen',subtitle:'A place to begin',flavor:'HOME, FOR NOW.',palette:['#88a565','#79995e','#627f4c'],wild:['spriglet','cindercub','ripplefin','mothglow','pebblit'],levels:[2,4],npcs:[{id:'guide',x:13,y:12,name:'Ranger Elowen',role:'guide'}],exits:[{x:27,y:8,to:'fen',tx:1,ty:8},{x:13,y:0,to:'whisperwood',tx:13,ty:16},{x:7,y:7,to:'resthouse',tx:14,ty:15},{x:20,y:7,to:'market',tx:14,ty:15}]},
    fen:{name:'Mosswater Fen',subtitle:'Where the river remembers',flavor:'FOLLOW THE FIREFLIES.',palette:['#799970','#6c8d67','#53795f'],wild:['reedle','mothglow','voltkit','ripplefin'],levels:[4,7],npcs:[{id:'fenhealer',x:5,y:8,name:'Traveling herbalist',role:'healer'},{id:'warden1',x:21,y:8,name:'Warden Sable',role:'warden',badge:'reed',team:[['reedle',5],['mothglow',6]]}],exits:[{x:0,y:8,to:'glen',tx:26,ty:8},{x:27,y:8,to:'verdantpass',tx:1,ty:8,requires:'reed'}]},
    verdantpass:{name:'Verdant Pass',subtitle:'The first road beyond the old Vale',flavor:'THE LONG ROAD BEGINS.',palette:['#71905d','#648455','#4e704d'],wild:['spriglet','mossboar','mothglow','voltkit'],levels:[6,9],route:1,npcs:[{id:'passguide',x:11,y:8,name:'Scout Rowan',role:'ranger'}],exits:[{x:0,y:8,to:'fen',tx:26,ty:8},{x:27,y:8,to:'stormmarsh',tx:1,ty:8}]},
    stormmarsh:{name:'Stormglass Marsh',subtitle:'Thunder sleeps beneath the water',flavor:'STEP WHERE THE REEDS BEND.',palette:['#587b70','#4d6e68','#3c5d5d'],wild:['reedle','voltkit','stormjay','mireling'],levels:[7,11],route:2,npcs:[{id:'marshcamp',x:6,y:8,name:'Storm camp',role:'healer'},{id:'warden_tide',x:21,y:8,name:'Warden Neris',role:'warden',badge:'tide',team:[['reedle',9],['coralisk',10]]}],exits:[{x:0,y:8,to:'verdantpass',tx:26,ty:8},{x:27,y:8,to:'emberbasin',tx:1,ty:8,requires:'tide'}]},
    emberbasin:{name:'Ember Basin',subtitle:'A valley shaped by living fire',flavor:'ASH FALLS LIKE SNOW.',palette:['#9a7050','#885f48','#6e4d43'],wild:['cindercub','emberwing','pebblit','glimmerbat'],levels:[9,13],route:3,npcs:[{id:'basincamp',x:6,y:8,name:'Ash camp',role:'healer'},{id:'warden_ember',x:21,y:8,name:'Warden Kael',role:'warden',badge:'ember',team:[['emberwing',11],['cindercub',12],['pebblit',11]]}],exits:[{x:0,y:8,to:'stormmarsh',tx:26,ty:8},{x:27,y:8,to:'frosthollow',tx:1,ty:8,requires:'ember'}]},
    frosthollow:{name:'Frost Hollow',subtitle:'A quiet valley of blue ice',flavor:'KEEP THE FIRE CLOSE.',palette:['#8da9a5','#789995','#637f83'],wild:['glimmerbat','stormjay','ripplefin','duskowl'],levels:[10,14],route:4,npcs:[{id:'frostkeeper',x:8,y:8,name:'Hearthkeeper Una',role:'healer'},{id:'frostguide',x:19,y:8,name:'Climber Tor',role:'ranger'}],exits:[{x:0,y:8,to:'emberbasin',tx:26,ty:8},{x:27,y:8,to:'shardmaze',tx:1,ty:8}]},
    shardmaze:{name:'The Shardmaze',subtitle:'Crystal paths with no straight answer',flavor:'REFLECTIONS CAN LIE.',palette:['#756e87','#68627b','#514f69'],wild:['glimmerbat','duskowl','mireling','voltkit'],levels:[11,15],route:5,npcs:[{id:'mazeguide',x:13,y:5,name:'Cartographer Pell',role:'ranger'}],exits:[{x:0,y:8,to:'frosthollow',tx:26,ty:8},{x:27,y:8,to:'ancientgarden',tx:1,ty:8}]},
    ancientgarden:{name:'Ancient Garden',subtitle:'A city reclaimed by roots',flavor:'GROWTH OUTLASTS STONE.',palette:['#657d55','#58714f','#465d47'],wild:['mossboar','spriglet','mothglow','duskowl'],levels:[12,16],route:6,npcs:[{id:'gardenboard',x:8,y:8,name:'Garden expedition board',role:'guild'},{id:'gardener',x:20,y:8,name:'Keeper Moss',role:'ranger'}],exits:[{x:0,y:8,to:'shardmaze',tx:26,ty:8},{x:27,y:8,to:'sunkensanctum',tx:1,ty:8}]},
    sunkensanctum:{name:'Sunken Sanctum',subtitle:'A temple beneath the inland sea',flavor:'BREATHE WITH THE TIDE.',palette:['#4d7776','#426c70','#365b66'],wild:['coralisk','mireling','ripplefin','reedle'],levels:[13,17],route:7,npcs:[{id:'sanctumcamp',x:7,y:8,name:'Diver’s refuge',role:'healer'},{id:'diver',x:20,y:8,name:'Diver Sio',role:'ranger'}],exits:[{x:0,y:8,to:'ancientgarden',tx:26,ty:8},{x:27,y:8,to:'cloudstep',tx:1,ty:8}]},
    cloudstep:{name:'Cloudstep Isles',subtitle:'Stone islands above the weather',flavor:'THE SKY HAS PATHS TOO.',palette:['#93a6a0','#829692','#6e817f'],wild:['stormjay','duskowl','emberwing','voltkit'],levels:[14,18],route:8,npcs:[{id:'skyhealer',x:7,y:8,name:'Wind shelter',role:'healer'},{id:'pilot',x:18,y:8,name:'Glider Iri',role:'ranger'}],exits:[{x:0,y:8,to:'sunkensanctum',tx:26,ty:8},{x:27,y:8,to:'starbridge',tx:1,ty:8}]},
    starbridge:{name:'Starbridge',subtitle:'The last crossing beneath the constellations',flavor:'ONLY COURAGE CROSSES.',palette:['#666c84','#595f77','#454c66'],wild:['stormjay','glimmerbat','duskowl','emberwing'],levels:[15,19],route:9,npcs:[{id:'warden_sky',x:21,y:8,name:'Warden Lyra',role:'warden',badge:'sky',team:[['stormjay',17],['duskowl',18],['glimmerbat',17]]}],exits:[{x:0,y:8,to:'cloudstep',tx:26,ty:8},{x:27,y:8,to:'aurorapeak',tx:1,ty:8,requires:'sky'}]},
    aurorapeak:{name:'Aurora Peak',subtitle:'Where every road meets the light',flavor:'THE BEACON IS NEAR.',palette:['#84938c','#74847f','#606f6e'],wild:['stormjay','solwyrm','glimmerbat','mossboar'],levels:[17,21],route:10,npcs:[{id:'aurorahealer',x:6,y:8,name:'Last-light camp',role:'healer'},{id:'pilgrim',x:19,y:8,name:'Pilgrim Vey',role:'ranger'}],exits:[{x:0,y:8,to:'starbridge',tx:26,ty:8},{x:27,y:8,to:'summit',tx:1,ty:8}]},
    summit:{name:'Starfall Ridge',subtitle:'At the edge of the sky',flavor:'THE OLD LIGHT WAITS.',palette:['#9aa08a','#8c957d','#7c8872'],wild:['pebblit','voltkit','duskowl','cindercub','stormjay'],levels:[18,22],npcs:[{id:'ridgehealer',x:5,y:8,name:'Beacon keeper',role:'healer'},{id:'warden2',x:15,y:8,name:'Warden Orin',role:'warden',badge:'stone',team:[['pebblit',19],['voltkit',20],['duskowl',19]]},{id:'beacon',x:23,y:5,name:'The sleeping beacon',role:'boss'}],exits:[{x:0,y:8,to:'aurorapeak',tx:26,ty:8},{x:24,y:4,to:'beaconhall',tx:14,ty:15,requires:'stone'}]},
    whisperwood:{name:'Whisperwood',subtitle:'A forest that changes its mind',flavor:'LISTEN BETWEEN THE LEAVES.',palette:['#537b55','#476d4d','#355b44'],wild:['spriglet','mothglow','mossboar','stormjay','glimmerbat'],levels:[5,9],npcs:[{id:'woodranger',x:9,y:8,name:'Ranger Fenn',role:'ranger'},{id:'woodboard',x:18,y:8,name:'Trail bounty board',role:'guild'}],exits:[{x:13,y:17,to:'glen',tx:13,ty:1},{x:0,y:8,to:'sunshore',tx:26,ty:8},{x:27,y:8,to:'moonruins',tx:1,ty:8,requires:'stone'}]},
    sunshore:{name:'Sunshore Coast',subtitle:'Salt, wind and hidden coves',flavor:'THE TIDE KEEPS SECRETS.',palette:['#92aa72','#829d67','#6e8b5c'],wild:['ripplefin','reedle','coralisk','emberwing'],levels:[6,10],npcs:[{id:'coasthealer',x:7,y:8,name:'Shore camp',role:'healer'},{id:'fisher',x:13,y:11,name:'Old Maren',role:'ranger'}],exits:[{x:27,y:8,to:'whisperwood',tx:1,ty:8}]},
    moonruins:{name:'Moonveil Ruins',subtitle:'Broken halls beneath the stars',flavor:'EVERY STONE REMEMBERS.',palette:['#777a70','#686d66','#555f5b'],wild:['duskowl','glimmerbat','emberwing','voltkit'],levels:[8,12],npcs:[{id:'ruinkeeper',x:8,y:9,name:'Archivist Nymm',role:'ranger'},{id:'ruinboard',x:19,y:9,name:'Ancient contract stone',role:'guild'}],exits:[{x:0,y:8,to:'whisperwood',tx:26,ty:8},{x:14,y:0,to:'crystaldepths',tx:14,ty:16}]},
    crystaldepths:{name:'Crystal Depths',subtitle:'The luminous world below',flavor:'LIGHT GROWS IN THE DARK.',palette:['#506d68','#46615e','#384e51'],wild:['glimmerbat','mireling','pebblit','coralisk'],levels:[10,14],npcs:[{id:'deephealer',x:6,y:9,name:'Cavern camp',role:'healer'},{id:'deepwarden',x:21,y:7,name:'Delver Iona',role:'ranger'}],exits:[{x:14,y:17,to:'moonruins',tx:14,ty:1}]},
    resthouse:{name:'Mira’s Rest House',subtitle:'Warm beds and familiar stories',flavor:'COME IN FROM THE WILD.',palette:['#b7a879','#a79770','#897f63'],wild:[],levels:[1,1],indoor:true,npcs:[{id:'mira',x:11,y:8,name:'Mira · Healing',role:'healer'},{id:'steward',x:17,y:8,name:'Nell · Sanctuary steward',role:'caretaker'}],exits:[{x:14,y:16,to:'glen',tx:7,ty:8}]},
    market:{name:'Tavi’s Trail Market',subtitle:'Useful things for difficult roads',flavor:'PACK FOR THE LONG WAY.',palette:['#b8a476','#a08c65','#806f54'],wild:[],levels:[1,1],indoor:true,npcs:[{id:'tavi',x:13,y:7,name:'Tavi · Trail supplies',role:'shop'},{id:'broker',x:18,y:7,name:'Bex · Expedition broker',role:'guild'}],exits:[{x:14,y:16,to:'glen',tx:20,ty:8}]},
    beaconhall:{name:'Beacon Hall',subtitle:'The chamber behind the light',flavor:'OLD FIRE, NEW PATHS.',palette:['#98977e','#858673','#6c776d'],wild:[],levels:[1,1],indoor:true,npcs:[{id:'hallkeeper',x:10,y:8,name:'Keeper Asha',role:'healer'},{id:'beaconarchive',x:18,y:8,name:'Beacon archive',role:'guild'}],exits:[{x:14,y:16,to:'summit',tx:24,ty:5}]}
  };
  const advantages={Grove:'Tide',Tide:'Ember',Ember:'Grove',Stone:'Spark',Spark:'Tide'};
  const api={species,areas,advantages,starters:['spriglet','cindercub','ripplefin'],SAVE_KEY:'emberwild-save-v1'};
  root.EWData=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
