/* Emberwild — original browser RPG. No runtime dependencies. */
(()=>{
 'use strict';
 const D=window.EWData,C=window.EWCore,A=window.EWArt,$=id=>document.getElementById(id);
 const canvas=$('world'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
 let state=null,battle=null,busy=false,battleFx='',muted=true,audio=null,musicTimer=null,musicStep=0,lastMove=0,modalKind='',storageOK=true,saveTimer=null;
 const modal=$('modal');
 const name=m=>D.species[m.species].name;
 function say(text){$('message').textContent=text;}
 function tone(freq=440,duration=.15,volume=.04,type='triangle'){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
  function musicTick(){if(muted||!document.body.classList.contains('game-active'))return;let world=[196,246.94,293.66,369.99,293.66,246.94];const area=state&&D.areas[state.area],route=area?.route||0;if(['fen','stormmarsh','sunkensanctum','sunshore'].includes(state?.area))world=[174.61,220,261.63,329.63,261.63,220];else if(route===3)world=[164.81,196,246.94,293.66,246.94,196];else if([4,5].includes(route)||state?.area==='crystaldepths')world=[220,277.18,329.63,440,329.63,277.18];else if(route>=8||state?.area==='summit')world=[246.94,293.66,369.99,493.88,369.99,293.66];else if(['whisperwood','moonruins','ancientgarden'].includes(state?.area))world=[146.83,196,233.08,293.66,233.08,196];const fight=[146.83,174.61,220,261.63],notes=battle?fight:world,n=notes[musicStep++%notes.length];tone(n,battle?.32:.7,battle?.018:.012,'sine');if(!battle&&musicStep%2===0)tone(n*2,.42,.006,'triangle');if(!battle&&musicStep%4===0)tone(n/2,1.05,.004,'sine');}
 function setSound(on){muted=!on;$('sound').textContent=muted?'Sound off':'Sound on';$('sound').setAttribute('aria-pressed',String(on));$('title-sound').textContent=muted?'♫ Start with sound':'♫ Sound is on';clearInterval(musicTimer);musicTimer=null;if(on){musicTick();musicTimer=setInterval(musicTick,700);}try{localStorage.setItem('emberwild-sound',on?'on':'off');}catch{}}
 function enterGame(){document.body.classList.add('game-active');$('title-screen').classList.add('closed');if(!muted)setSound(true);setTimeout(()=>canvas.focus(),80);}
 function save(manual=false){if(!state||battle)return;try{localStorage.setItem(D.SAVE_KEY,JSON.stringify(state));storageOK=true;$('save-status').textContent='SAVED LOCALLY';if(manual)say('Progress saved in this browser. Export a backup in Save & settings.');}catch{storageOK=false;$('save-status').textContent='SAVE UNAVAILABLE';if(manual)say('Browser storage is unavailable. Use Save & settings → Export save to keep your progress.');}}
 function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(),300);}
 function sprites(container=document){container.querySelectorAll('canvas[data-species]').forEach(c=>{c.width=96;c.height=96;A.creature(c.getContext('2d'),c.dataset.species,0,0,96);});}
 function hp(m){return `<div class="hp-track"><span style="width:${100*m.hp/C.stats(m).maxHp}%;background:${m.hp<C.stats(m).maxHp*.3?'#c78664':'#79a174'}"></span></div>`;}
 function quest(){if(!state)return ['A new beginning','Choose a companion and begin your journey through the Vale.'];if(state.completed)return ['Beyond the beacon',`The old paths are open. Explore the entire Vale and discover ${Object.keys(D.species).length-state.caught.length} remaining species.`];if(state.badges.includes('stone'))return ['Wake the beacon','All five crests answer you. Approach the crystal at Starfall Ridge and face the final guardians.'];if(state.badges.includes('sky'))return ['The final ascent','Cross Aurora Peak to Starfall Ridge, then earn Orin’s Stone Crest.'];if(state.badges.includes('ember'))return ['Across the far country','Continue through Frost Hollow, the Shardmaze, Ancient Garden, Sunken Sanctum and Cloudstep. Warden Lyra waits at Starbridge.'];if(state.badges.includes('tide'))return ['Through fire and ice','Enter Ember Basin and earn Kael’s Ember Crest before crossing Frost Hollow.'];if(state.badges.includes('reed'))return ['The long road','The Reed Crest opens Verdant Pass. Cross it to Stormglass Marsh and challenge Warden Neris.'];return ['Follow the embers','Build your party and earn Sable’s Reed Crest in Mosswater Fen. The beacon is now a long journey beyond the eastern road.'];}
 function renderHUD(){
   const a=D.areas[state?.area||'glen'];$('location').textContent=a.name;$('region-label').textContent=a.subtitle;$('scene-label').innerHTML=`${a.name.toUpperCase()}<small>${a.flavor}</small>`;
   const [title,copy]=quest();$('quest-title').textContent=title;$('quest-copy').textContent=copy;
   const required=['reed','tide','ember','sky','stone'],steps=[['Choose your first companion',!!state],['Earn all five guardian crests',required.every(b=>state?.badges.includes(b))],['Awaken the ancient beacon',state?.completed]];
   $('quest-steps').innerHTML=steps.map(([text,done])=>`<div class="quest-step ${done?'done':''}"><i>${done?'✓':''}</i>${text}</div>`).join('');
   $('orbs').textContent=state?.orbs??8;$('potions').textContent=state?.potions??5;$('coins').textContent=state?.coins??60;$('team-count').textContent=`${state?.team.length??0} / 12`;
   $('team').innerHTML=state?state.team.slice(0,3).map((m,i)=>`<div class="companion-row"><canvas data-species="${m.species}" aria-label="${name(m)}"></canvas><div class="details"><strong>${name(m)}${state.active===i?' ✦':''}</strong> <small>Lv. ${m.level}</small>${hp(m)}<small>${D.species[m.species].type} · ${m.hp}/${C.stats(m).maxHp} HP</small></div></div>`).join('')+(state.team.length>3?`<small class="empty-team">+ ${state.team.length-3} in your sanctuary</small>`:''):'<p class="empty-team">A new friend is waiting for you.</p>';
   $('mode-label').textContent=battle?'IN BATTLE':'EXPLORING';$('scene-label').hidden=!!battle;$('viewport').classList.toggle('battling',!!battle);$('viewport').closest('.game-column').classList.toggle('in-battle',!!battle);sprites($('team'));updateHint();updateOnlineStatus();
 }
 function welcome(){
   $('overlay').hidden=false;$('overlay').innerHTML=`<div class="welcome"><p class="eyebrow">WELCOME TO THE VALE</p><h2>A small spark. A lifelong bond.</h2><p>The ancient beacon has gone quiet. Choose the companion who will help you bring its light back to the Vale.</p><div class="starter-list">${D.starters.map(id=>`<button class="starter-card" data-starter="${id}"><canvas data-species="${id}" aria-label="${D.species[id].name}"></canvas><strong>${D.species[id].name}</strong><small>${id==='spriglet'?'Steady & spirited':id==='cindercub'?'Bold & bright':'Calm & curious'}</small><span class="type" style="background:${D.species[id].color}">${D.species[id].type}</span></button>`).join('')}</div><p class="footnote">Choose any companion. Every path can lead to the light.</p></div>`;
   sprites($('overlay'));$('overlay').querySelectorAll('[data-starter]').forEach(btn=>btn.onclick=()=>{state=C.initial(btn.dataset.starter);$('overlay').hidden=true;renderHUD();save();tone(660);say(`${name(state.team[0])} is ready! Walk through the grass below the rest house, or head east toward Mosswater Fen. Press E beside people to talk.`);canvas.focus();});renderHUD();
 }
 function openModal(title,body,kind='info'){
   modalKind=kind;$('modal-content').innerHTML=`<div class="modal-heading"><h2>${title}</h2><button id="close-modal" aria-label="Close dialog">×</button></div>${body}`;
   $('close-modal').onclick=()=>modal.close();if(!modal.open)modal.showModal();document.body.classList.add('modal-open');sprites(modal);
 }
 modal.addEventListener('close',()=>{document.body.classList.remove('modal-open');modalKind='';canvas.focus();});
 function nearby(){if(!state)return null;return D.areas[state.area].npcs.find(n=>Math.abs(n.x-state.x)+Math.abs(n.y-state.y)<=1);}
  function updateHint(){const n=nearby();$('interaction-hint').hidden=!n||!!battle||!state;$('interaction-hint').textContent=n?`E · ${n.name}`:'';}
  function areaTransition(){document.body.classList.remove('area-shift');void document.body.offsetWidth;document.body.classList.add('area-shift');musicStep=0;setTimeout(()=>document.body.classList.remove('area-shift'),760);}
 function move(dx,dy,dir){
   if(!state||battle||modal.open||!$('overlay').hidden)return;state.facing=dir;const x=state.x+dx,y=state.y+dy;
   if(!C.passable(state.area,x,y)){updateHint();return;}
   state.x=x;state.y=y;state.steps++;EWOnline.setLocal(state);EWOnline.update(state);
   const exit=D.areas[state.area].exits.find(e=>e.x===x&&e.y===y);
      if(exit){if(exit.requires&&!state.badges.includes(exit.requires)){state.x-=dx;state.y-=dy;const crest=exit.requires[0].toUpperCase()+exit.requires.slice(1);say(`This trail opens to bearers of the ${crest} Crest. Find the region’s warden and complete their challenge.`);}else if(exit.requiresClaim&&!state.claimed.includes(exit.requiresClaim)){state.x-=dx;state.y-=dy;say('A living root seals the passage. Defeat the guardian of Hollowroot Well first.');}else{state.area=exit.to;state.x=exit.tx;state.y=exit.ty;if(!state.discovered.includes(state.area))state.discovered.push(state.area);areaTransition();tone(540);say(`You arrived in ${D.areas[state.area].name}. ${D.areas[state.area].subtitle}.`);}EWOnline.setLocal(state);EWOnline.update(state);renderHUD();scheduleSave();return;}
   if(C.tile(state.area,x,y)==='grass'&&state.steps%3===0&&Math.random()<.48){startBattle('wild');return;}
   updateHint();scheduleSave();
 }
 function interact(){
   if(!state||battle||modal.open)return;const n=nearby();if(!n){say('Stand beside a person or the beacon, then press E to interact.');return;}
   tone(520);
   if(n.role==='healer'){C.heal(state);document.body.classList.remove('restored');void document.body.offsetWidth;document.body.classList.add('restored');setTimeout(()=>document.body.classList.remove('restored'),900);tone(760,.3,.04);if(state.orbs===0){state.orbs=3;say('Your companions are fully rested. Take three spare bindstones, on the house.');}else say('Your companions are fully rested. Safe travels — come back any time!');save();renderHUD();}
   else if(n.role==='shop')shop();
   else if(n.role==='caretaker'){team();}
   else if(n.role==='guild'){bounties(n.name);}
   else if(n.role==='cache'){trailCache(n);}
   else if(n.role==='questgiver'){questGiver(n);}
   else if(n.role==='landmark'){openModal('The Hollowroot notice','<p class="modal-copy">Three nights ago, an explorer followed strange lights into the abandoned well. The pathfinders need someone brave enough to search the flooded passages.</p><div class="modal-buttons"><button id="open-quests" class="primary">Open quest log</button></div>');$('open-quests').onclick=questLog;}
   else if(n.role==='miniboss'||n.role==='regionalboss'){
     const defeated=state.claimed.includes('defeated-'+n.id);if(defeated){openModal(n.name,`<p class="modal-copy">${n.role==='regionalboss'?'The ancient guardian rests beneath a canopy of quiet roots.':'Gloomfang watches from the shadows, no longer hostile.'}</p>`);return;}
     openModal(n.name,`<section class="boss-warning"><span>${n.role==='regionalboss'?'♜':'⚔'}</span><div><p class="eyebrow">${n.role==='regionalboss'?'REGIONAL BOSS':'MINIBOSS'}</p><h3>${n.name}</h3><p>${n.role==='regionalboss'?'A two-phase guardian battle. Prepare your strongest party.':'A dangerous optional guardian blocks the sealed passage.'}</p></div></section><div class="modal-buttons"><button id="elite-fight" class="primary">Begin battle</button><button id="elite-later">Prepare first</button></div>`);
     $('elite-fight').onclick=()=>{modal.close();startBattle(n.role==='regionalboss'?'regional':'elite',n);};$('elite-later').onclick=()=>modal.close();
   }
   else if(n.role==='ranger'){
     const lore={woodranger:'“Whisperwood rearranges its trails, but the pale stones always point home. Sunshore lies west. The sealed ruins wait to the east.”',fisher:'“Coralisk rides the foam at low tide. Emberwing appears when the evening wind turns warm.”',ruinkeeper:'“The crystals beneath these halls are older than the beacon. Glimmerbat can hear their memories.”',deepwarden:'“You made it to the deepest trail. Creatures down here are strong; rotate your party and use the cavern camp.”'};
     openModal(n.name,`<p class="modal-copy">${lore[n.id]||'“The Vale grows wider for anyone willing to leave the familiar trail.”'}</p><p class="modal-copy">This region’s wild companions range from level ${D.areas[state.area].levels[0]} to ${D.areas[state.area].levels[1]}.</p>`);
   }
   else if(n.role==='guide')openModal('A word from Elowen',`<div class="modal-copy"><p>“The beacon once held the Vale together. When its light faded, the eastern road broke into dangerous country.”</p><p>“Five guardian crests are needed now: Reed, Tide, Ember, Sky and Stone. Sable holds the first in Mosswater Fen. The road beyond her crosses ten distant regions before Starfall Ridge.”</p><p>“Train a varied party, use every refuge, and return to Tavi when supplies run low. Your first companion evolves at level 8.”</p></div><div class="modal-buttons"><button id="supplies" class="primary" ${state.claimed.includes('elowen')?'disabled':''}>${state.claimed.includes('elowen')?'Supplies collected':'Take ranger supplies'}</button></div>`);
   else if(n.role==='warden'){
     if(state.badges.includes(n.badge)){openModal(n.name,'<p class="modal-copy">“You carry our crest with honor. The next road is open. Keep your companions close.”</p>');return;}
     openModal(n.name,`<div class="modal-copy"><p>“A guardian crest is earned through trust. Show me the bond you share with your companions.”</p><p>Challenge: ${n.team.map(([id,lv])=>`${D.species[id].name} · Lv. ${lv}`).join(', ')}. Your team will be healed and supplied on victory.</p></div><div class="modal-buttons"><button class="primary" id="challenge">Begin challenge</button><button id="later">Come back later</button></div>`);
     $('challenge').onclick=()=>{modal.close();startBattle('warden',n);};$('later').onclick=()=>modal.close();
   }else if(n.role==='boss'){
     if(state.completed){openModal('The beacon shines',`<p class="modal-copy">Warm light spills across the Vale. You and your companions have given this place a new beginning.</p><p class="modal-copy">Your story continues: discover all ${Object.keys(D.species).length} species, raise your companions, and explore at your own pace.</p>`);return;}
     const crests=['reed','tide','ember','sky','stone'];if(!crests.every(b=>state.badges.includes(b))){say('Five crest-shapes circle the stone. Complete the long eastern route and earn every guardian crest first.');return;}
     if(state.team.length>=12){say('Make one space in your sanctuary before awakening the beacon. A new companion is waiting.');return;}
     openModal('The sleeping beacon','<p class="modal-copy">All five crests hum in your hands. Beyond the crystal, powerful Duskowl and Solwyrm stir. One final trial will decide whether the old light returns.</p><div class="modal-buttons"><button id="awaken" class="primary">Awaken the beacon</button></div>');$('awaken').onclick=()=>{modal.close();startBattle('boss');};
   }
   if($('supplies'))$('supplies').onclick=()=>{if(state.claimed.includes('elowen'))return;state.claimed.push('elowen');state.orbs+=4;state.potions+=2;C.claimQuest(state,'first_steps');save();renderHUD();modal.close();say('First Steps complete! Elowen gave you supplies, a Moonleaf and 20 shards. “Bring the light home.”');};
 }
  function shop(note=''){
    const card=(item,amount,cost,icon,title,tag,copy,badge='')=>`<button class="shop-card ${state.coins<cost?'too-costly':''}" data-buy="${item},${amount},${cost}"><span class="wares-icon ${item}">${icon}</span><span class="wares-copy"><em>${tag}</em><strong>${title}</strong><small>${copy}</small></span><span class="shop-price"><b>${cost}</b><small>SHARDS</small></span>${badge?`<i>${badge}</i>`:''}</button>`;
    openModal('Tavi’s trail market',`<section class="shop-hero"><div class="tavi-portrait" aria-hidden="true"><span></span></div><div class="shop-welcome"><p class="eyebrow">OPEN FROM FIRST LIGHT TO FIREFLY HOUR</p><h3>“A prepared ranger gets the better story.”</h3><small>— Tavi, trail outfitter</small></div><div class="market-wallet"><span>◆</span><div><small>YOUR SHARD PURSE</small><strong>${state.coins}</strong></div></div></section><div class="market-stock"><span>FIELD SUPPLIES</span><small>Your pack: ${state.orbs} bindstones · ${state.potions} tonics</small></div><div class="shop-grid">${card('orbs',1,15,'◒','1 Bindstone','CAPTURE','Befriend one wild companion.')}${card('orbs',5,60,'◉','5 Bindstones','BEST VALUE','Enough for a long expedition.','SAVE 15')}${card('potions',1,20,'✚','1 Trail Tonic','RECOVERY','Restore 40 HP in or out of battle.')}${card('potions',3,50,'✚','3-Tonic Case','TRAIL PACK','Three sealed restorative tonics.','SAVE 10')}${card('kit',1,95,'▣','Warden’s Expedition Kit','FULL LOADOUT','5 bindstones + 3 tonics.','POPULAR')}<button class="shop-card service ${state.coins<25?'too-costly':''}" id="market-heal"><span class="wares-icon heal">✦</span><span class="wares-copy"><em>IN-STORE SERVICE</em><strong>Party Treatment</strong><small>Fully restore every companion.</small></span><span class="shop-price"><b>25</b><small>SHARDS</small></span></button></div><p class="shop-receipt ${note?'active':''}" role="status"><span>${note?'✓':'✦'}</span>${note||'Choose any supply. Tavi packs it immediately.'}</p>`,'shop');
   modal.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const [item,amount,cost]=b.dataset.buy.split(',');buy(item,Number(cost),Number(amount));});$('market-heal').onclick=()=>{if(state.coins<25)return shop('You need 25 shards for a party treatment.');state.coins-=25;C.heal(state);save();renderHUD();tone(760);shop('Your entire party is fully restored.');};
 }
  function buy(item,cost,amount=1){if(state.coins<cost){shop(`You need ${cost-state.coins} more shards. Win battles or complete bounties.`);return;}state.coins-=cost;if(item==='kit'){state.orbs+=5;state.potions+=3;}else state[item]+=amount;save();renderHUD();tone(700);shop('Packed and ready. Safe travels!');}
  function trailCache(n){
    const found=state.claimed.includes(n.id),r=n.reward||{},rewards=[r.coins?`${r.coins} shards`:'',r.orbs?`${r.orbs} bindstone${r.orbs===1?'':'s'}`:'',r.potions?`${r.potions} tonic${r.potions===1?'':'s'}`:''].filter(Boolean).join(' · ');
    openModal(n.name,`<section class="discovery-card"><span>${found?'✓':'✦'}</span><div><p class="eyebrow">${found?'TRAIL SECRET DISCOVERED':'HIDDEN TRAIL CACHE'}</p><h3>${found?'You found this secret.':'Something glints off the main road.'}</h3><p>${found?'The container is empty, but its mark remains in your journal.':`Inside: <strong>${rewards}</strong>.`}</p></div></section>${found?'':`<div class="modal-buttons"><button id="claim-cache" class="primary">Open cache</button></div>`}`,'cache');
    if($('claim-cache'))$('claim-cache').onclick=()=>{state.claimed.push(n.id);state.coins+=r.coins||0;state.orbs+=r.orbs||0;state.potions+=r.potions||0;if(r.item)state.inventory[r.item]=(state.inventory[r.item]||0)+1;save();renderHUD();tone(920,.35,.05);trailCache(n);};
  }
  function questGiver(n){
    const cards=n.quests.map(id=>{const q=D.quests[id],status=state.quests[id],p=C.questProgress(state,q),ready=status==='active'&&p>=q.objective.amount;return `<article class="quest-card ${status||'available'}"><div><p class="eyebrow">${status==='complete'?'COMPLETED':ready?'READY TO TURN IN':status==='active'?'ACTIVE QUEST':'NEW QUEST'}</p><h3>${q.title}</h3><p>${q.description}</p><small>${Math.min(p,q.objective.amount)} / ${q.objective.amount} · Reward: ${rewardText(q.reward)}</small></div><button data-quest="${id}" ${status==='complete'?'disabled':''}>${status==='complete'?'Complete':ready?'Claim reward':status==='active'?'View progress':'Accept quest'}</button></article>`;}).join('');
    openModal(n.name,`<p class="modal-copy">“Every path has a story. Choose the work that calls to you.”</p><div class="quest-list">${cards}</div>`,'quests');
    modal.querySelectorAll('[data-quest]').forEach(b=>b.onclick=()=>{const id=b.dataset.quest,q=D.quests[id];if(!state.quests[id]){state.quests[id]='active';tone(660);say(`Quest accepted: ${q.title}.`);}else if(C.claimQuest(state,id)){tone(920,.3,.05);say(`Quest complete: ${q.title}. Reward collected.`);}else{say(`${q.title}: ${C.questProgress(state,q)} / ${q.objective.amount}.`);}save();renderHUD();questGiver(n);});
  }
  function rewardText(r={}){return [r.coins&&`${r.coins} shards`,r.orbs&&`${r.orbs} bindstones`,r.potions&&`${r.potions} tonics`,r.item&&`${r.amount||1} ${D.items[r.item].name}`].filter(Boolean).join(' · ');}
  function questLog(){
    if(!state)return;const entries=Object.entries(D.quests),active=entries.filter(([id])=>state.quests[id]==='active'),available=entries.filter(([id])=>!state.quests[id]),done=entries.filter(([id])=>state.quests[id]==='complete');const list=(arr,empty)=>arr.length?arr.map(([id,q])=>{const p=C.questProgress(state,q),ready=p>=q.objective.amount;return `<article class="quest-card ${ready?'ready':''}"><div><p class="eyebrow">${ready?'OBJECTIVE COMPLETE':q.giver}</p><h3>${q.title}</h3><p>${q.description}</p><span class="quest-track"><i style="width:${Math.min(100,p/q.objective.amount*100)}%"></i></span><small>${Math.min(p,q.objective.amount)} / ${q.objective.amount} · ${rewardText(q.reward)}</small></div></article>`;}).join(''):`<p class="empty-team">${empty}</p>`;openModal('Quest log',`<section class="quest-summary"><span>✦</span><div><p class="eyebrow">RANGER LEVEL ${state.playerLevel}</p><h3>${active.length} active · ${done.length} complete</h3><small>${state.playerXp}/${state.playerLevel*80} ranger experience</small></div></section><h3 class="journal-subhead">Active adventures</h3><div class="quest-list">${list(active,'Speak with people marked by a golden ! to find quests.')}</div><h3 class="journal-subhead">Available rumors</h3><div class="quest-list compact">${list(available,'Every local quest has been accepted.')}</div><h3 class="journal-subhead">Completed</h3><p class="modal-copy">${done.length?done.map(([,q])=>'✓ '+q.title).join(' · '):'No completed quests yet.'}</p>`,'quests');
  }
  function inventory(){
    if(!state)return;const owned=Object.entries(D.items).map(([id,item])=>[id,item,id==='bindstone'?state.orbs:id==='tonic'?state.potions:(state.inventory[id]||0)]).filter(([, ,n])=>n>0);openModal('Ranger satchel',`<section class="quest-summary"><span>▱</span><div><p class="eyebrow">FIELD INVENTORY</p><h3>${owned.length} item types · ${state.coins} shards</h3><small>Materials, supplies, equipment and key discoveries</small></div></section><div class="inventory-grid">${owned.map(([id,i,n])=>`<article class="inventory-card"><span>${i.category==='Consumable'?'✚':i.category==='Capture'?'◒':i.category==='Key item'?'✦':i.category==='Equipment'?'◇':'◆'}</span><div><em>${i.rarity} · ${i.category}</em><strong>${i.name}</strong><p>${i.description}</p></div><b>×${n}</b></article>`).join('')}</div>`,'inventory');
  }
  function bounties(title='Expedition board'){
    const jobs=[{id:'wins5',icon:'⚔',name:'Trail tested',copy:'Win 5 battles',value:state.wins,goal:5,reward:'60 shards',give:()=>state.coins+=60},{id:'species6',icon:'◒',name:'Field researcher',copy:'Discover 6 species',value:state.caught.length,goal:6,reward:'4 bindstones',give:()=>state.orbs+=4},{id:'story',icon:'✦',name:'Lightbringer',copy:'Restore the ancient beacon',value:state.completed?1:0,goal:1,reward:'120 shards',give:()=>state.coins+=120},{id:'species15',icon:'◇',name:'Deep-delver journal',copy:'Discover 15 species',value:state.caught.length,goal:15,reward:'8 stones + 5 tonics',give:()=>{state.orbs+=8;state.potions+=5;}}];jobs.forEach(j=>j.ready=j.value>=j.goal);
    openModal(title,`<section class="board-hero"><span>✦</span><div><p class="eyebrow">VALE RANGERS’ GUILD</p><h3>Expedition contracts</h3><small>Progress is shared across every board. Each reward can be claimed once.</small></div></section><div class="bounty-list">${jobs.map(j=>{const claimed=state.claimed.includes('bounty-'+j.id),progress=Math.min(100,Math.round(j.value/j.goal*100));return `<div class="bounty-row ${claimed?'claimed':''}"><span class="bounty-icon">${j.icon}</span><div><strong>${j.name}</strong><small>${j.copy} · ${Math.min(j.value,j.goal)}/${j.goal}</small><span class="contract-track"><i style="width:${progress}%"></i></span></div><span class="bounty-reward"><small>REWARD</small><b>${j.reward}</b></span><button data-bounty="${j.id}" ${claimed||!j.ready?'disabled':''}>${claimed?'Claimed':j.ready?'Claim reward':'In progress'}</button></div>`;}).join('')}</div>`,'bounties');
   modal.querySelectorAll('[data-bounty]').forEach(b=>b.onclick=()=>{const job=jobs.find(j=>j.id===b.dataset.bounty);if(!job||!job.ready||state.claimed.includes('bounty-'+job.id))return;state.claimed.push('bounty-'+job.id);job.give();save();renderHUD();tone(820);bounties(title);});
 }
 function startBattle(kind,npc){save();battle=C.beginBattle(state,kind,npc);tone(220);renderHUD();renderBattle();}
 function renderBattle(){
   const layer=$('battle-layer');if(!battle){layer.hidden=true;return;}layer.hidden=false;
   const m=state.team[state.active],e=battle.enemies[battle.index],ally=D.species[m.species],foe=D.species[e.species],effective=D.advantages[ally.type]===foe.type,ability=D.abilities[ally.skill];
   const label=battle.kind==='wild'?'WILD ENCOUNTER':battle.kind==='boss'?'THE BEACON TRIAL':battle.kind==='elite'?'MINIBOSS':battle.kind==='regional'?`REGIONAL BOSS · PHASE ${battle.phase}`:'WARDEN CHALLENGE';
   layer.innerHTML=`<div class="battle-scene ${battleFx?'fx-'+battleFx:''} ${battle.kind==='regional'?'boss-arena':''}"><span class="battle-badge">${label} · ${battle.index+1}/${battle.enemies.length}</span><canvas class="battle-creature enemy" data-species="${e.species}" aria-label="${name(e)}"></canvas><canvas class="battle-creature ally" data-species="${m.species}" aria-label="${name(m)}"></canvas><div class="battle-info enemy"><strong>${name(e)}</strong><small>Lv. ${e.level}</small>${hp(e)}<p><span class="type-chip">${foe.type}</span> ${e.hp}/${C.stats(e).maxHp} HP ${battle.enemyStatus?`· <b class="status-chip">${battle.enemyStatus.kind}</b>`:''}</p></div><div class="battle-info ally"><strong>${name(m)}</strong><small>Lv. ${m.level}</small>${hp(m)}<p><span class="type-chip">${ally.type}</span> ${m.hp}/${C.stats(m).maxHp} HP · <b>${'◆'.repeat(battle.energy)}${'◇'.repeat(3-battle.energy)}</b></p></div><div class="battle-panel"><div class="battle-message"><span>✦</span><p role="status" aria-live="polite">${battle.log}</p></div><div class="battle-actions">${battle.ended?'<button id="continue-battle" class="battle-continue">Continue adventure <b>→</b></button>':`<button class="battle-command attack" data-action="strike" ${busy?'disabled':''}><b>⚔</b><span><strong>Strike</strong><small>Attack · gain 1 focus</small></span></button><button class="battle-command skill" data-action="skill" ${battle.energy<1||busy?'disabled':''}><b>✦</b><span><strong>${ally.skill}</strong><small>${ability?.description||ally.type+' skill'}${effective?' · Strong!':''}</small></span></button><button class="battle-command" data-action="catch" ${battle.kind!=='wild'||state.orbs<1||state.team.length>=12||busy?'disabled':''}><b>◒</b><span><strong>Capture</strong><small>${state.orbs} bindstones · weaken first</small></span></button><button class="battle-command" data-action="potion" ${state.potions<1||busy?'disabled':''}><b>✚</b><span><strong>Use tonic</strong><small>${state.potions} left · restore 40 HP</small></span></button><button class="battle-command" data-action="switch" ${busy?'disabled':''}><b>↻</b><span><strong>Party & guard</strong><small>Switch or reduce the next hit</small></span></button><button class="battle-command" data-action="run" ${battle.kind!=='wild'||busy?'disabled':''}><b>↩</b><span><strong>Leave battle</strong><small>${battle.kind==='wild'?'Escape safely':'Cannot leave this challenge'}</small></span></button>`}</div></div></div>`;
   sprites(layer);layer.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=()=>{if(btn.dataset.action==='switch'){battleSwitch();return;}act(btn.dataset.action);});
   if($('continue-battle'))$('continue-battle').onclick=()=>{const wonStory=battle.kind==='boss'&&battle.outcome==='won',wonRegion=battle.kind==='regional'&&battle.outcome==='won',log=battle.log;battle=null;renderBattle();renderHUD();save();say(log);if(wonStory)openModal('You brought the light home.',`<p class="eyebrow">CHAPTER 01 · COMPLETE</p><p class="modal-copy">From the little paths of Briar Glen to the stones of Starfall Ridge, every companion carried a piece of the light. Now the Vale shines again.</p><p class="modal-copy">Solwyrm has joined your team. You can keep exploring and fill your journal. Thank you for playing Emberwild.</p><div class="modal-buttons"><button id="credits-journal" class="primary">View your field journal</button></div>`);else if(wonRegion)openModal('The roots are at peace.',`<p class="eyebrow">BRIAR GLEN ADVENTURE COMPLETE</p><p class="modal-copy">The Rootwarden recognizes you as a Pathfinder. New light runs through Hollowroot Well, and the village above is safe.</p><div class="modal-buttons"><button id="region-quests" class="primary">View quest log</button></div>`);if($('credits-journal'))$('credits-journal').onclick=journal;if($('region-quests'))$('region-quests').onclick=questLog;canvas.focus();};
 }
 function act(action,target){if(!battle||busy)return;busy=true;battleFx=action==='catch'?'capture':action==='potion'?'heal':action==='guard'?'guard':'attack';renderBattle();tone(action==='catch'?760:action==='potion'?620:260,.2,.045);setTimeout(()=>{if(!battle){busy=false;return;}C.battleAction(state,battle,action,target);battleFx='impact';renderHUD();renderBattle();tone(battle.ended&&battle.outcome==='won'?880:360,.2,.035);setTimeout(()=>{busy=false;battleFx='';if(battle)renderBattle();},260);},230);}
 function battleSwitch(){openModal('Change tactics',`<p class="modal-copy">Switching uses your turn. Guard reduces the next hit and restores one focus.</p><div class="modal-buttons"><button id="guard" class="primary">Guard this turn</button>${state.team.map((m,i)=>`<button data-switch="${i}" ${i===state.active||m.hp<=0?'disabled':''}>${name(m)} · ${m.hp} HP</button>`).join('')}</div>`);$('guard').onclick=()=>{modal.close();act('guard');};modal.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>{modal.close();act('switch',Number(b.dataset.switch));});}
 function team(){
   if(!state)return;if(battle){if(!battle.ended)battleSwitch();return;}
   openModal('Your companions',`<p class="modal-copy">Your lead companion enters battle first. All healthy companions share experience. Visit a healer for free recovery.</p>${state.team.map((m,i)=>`<div class="roster-card"><canvas data-species="${m.species}" aria-label="${name(m)}"></canvas><div class="details"><strong>${name(m)} · Lv. ${m.level}</strong><small>${D.species[m.species].type} · ${m.hp}/${C.stats(m).maxHp} HP · XP ${m.xp}/${m.level*14}</small>${hp(m)}<small>${D.species[m.species].evolve?'Evolves at level 8':'Fully awakened'}</small></div><button data-lead="${i}" ${i===state.active||m.hp<=0?'disabled':''}>${i===state.active?'Lead':'Set lead'}</button><button data-heal="${i}" ${state.potions<1||m.hp===C.stats(m).maxHp?'disabled':''}>Tonic</button><button data-release="${i}" ${state.team.length===1?'disabled':''} aria-label="Release ${name(m)}">↗</button></div>`).join('')}`,'team');
   modal.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>{state.active=Number(b.dataset.lead);save();renderHUD();team();});
   modal.querySelectorAll('[data-heal]').forEach(b=>b.onclick=()=>{const m=state.team[Number(b.dataset.heal)];state.potions--;m.hp=Math.min(C.stats(m).maxHp,m.hp+40);save();renderHUD();team();});
   modal.querySelectorAll('[data-release]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.release);openModal('Release a companion?',`<p class="modal-copy">${name(state.team[i])} will return to the wild. Its journal entry stays discovered. This cannot be undone.</p><div class="modal-buttons"><button id="confirm-release">Release ${name(state.team[i])}</button><button id="cancel-release" class="primary">Keep companion</button></div>`);$('cancel-release').onclick=team;$('confirm-release').onclick=()=>{state.team.splice(i,1);state.active=0;if(!state.team.some(m=>m.hp>0))C.heal(state);state.active=state.team.findIndex(m=>m.hp>0);save();renderHUD();team();};});
 }
 function journal(){
    if(!state)return;const [title,copy]=quest(),regions=Object.entries(D.areas).filter(([,a])=>!a.indoor),crestNames=[['reed','Reed'],['tide','Tide'],['ember','Ember'],['sky','Sky'],['stone','Stone']],secrets=state.claimed.filter(id=>id.includes('cache')).length;openModal('Field journal',`<p class="eyebrow">${state.caught.length} / ${Object.keys(D.species).length} SPECIES DISCOVERED · ${state.wins} BATTLES WON · ${secrets} SECRETS</p><h2>${title}</h2><p class="modal-copy">${copy}</p><div class="modal-buttons"><button id="journal-quests" class="primary">Quest log</button><button id="journal-inventory">Inventory</button></div><p class="modal-copy">Crests: ${crestNames.map(([id,label])=>state.badges.includes(id)?`✦ ${label}`:`○ ${label}`).join(' &nbsp; ')}</p><h3 class="journal-subhead">Vale atlas</h3><div class="atlas">${regions.map(([id,a])=>`<div class="atlas-place ${state.area===id?'current':state.discovered.includes(id)?'':'unknown'}"><span>${state.area===id?'⌖':state.discovered.includes(id)?'◇':'?'}</span><strong>${state.discovered.includes(id)?a.name:'Uncharted'}</strong><small>${state.discovered.includes(id)?a.subtitle:'Explore to reveal this place'}</small></div>`).join('')}</div><h3 class="journal-subhead">Companion journal</h3><div class="codex-grid">${Object.entries(D.species).map(([id,s])=>`<div class="codex-card">${state.caught.includes(id)?`<canvas data-species="${id}" aria-label="${s.name}"></canvas><strong>${s.name}</strong><small>${s.type}</small><p>${s.description}</p>`:`<div style="font-size:40px;opacity:.2">✧</div><strong>Undiscovered</strong><small>${s.type} companion</small>`}</div>`).join('')}</div>`,'journal');$('journal-quests').onclick=questLog;$('journal-inventory').onclick=inventory;
 }
  function help(){openModal('A ranger’s guide',`<div class="modal-copy"><p><strong>Explore:</strong> WASD or arrow keys to walk. Press E or Space beside a person, door, chest or landmark to interact. J opens the journal, T opens your party, and Escape opens the pause menu. On a phone, use the controls beneath the world.</p><p><strong>Look beyond the road:</strong> Every region on the long eastern expedition has a side trail and one hidden supply cache. Ten secrets are recorded in the field journal.</p><p><strong>Buildings:</strong> Walk onto a marked doorway to enter. Mira’s Rest House heals and manages your party. Tavi’s Trail Market sells items and expedition kits. Expedition boards pay milestone rewards.</p><p><strong>Find companions:</strong> Walk through tall grass. Weaken a wild creature, then throw a bindstone. Later regions contain higher-level opponents, so train more than one companion.</p><p><strong>Battle:</strong> Strike restores focus; the elemental skill spends it. Party & guard opens switching and defense choices. Tonics heal, Capture uses bindstones, and Leave works in wild encounters.</p></div><table class="type-table"><thead><tr><th>Attacking element</th><th>Strong against</th></tr></thead><tbody>${Object.entries(D.advantages).map(([a,b])=>`<tr><td>${a}</td><td>${b}</td></tr>`).join('')}</tbody></table><div class="modal-copy"><p><strong>Main quest:</strong> Earn five crests in order: Reed, Tide, Ember, Sky and Stone. The route passes through ten distinct regions between Mosswater Fen and Starfall Ridge. The final beacon trial reaches level 23.</p><p><strong>Optional frontier:</strong> The northern Briar Glen trail leads to Whisperwood, Sunshore Coast, Moonveil Ruins and the Crystal Depths.</p><p><strong>Saving:</strong> Progress saves in this browser outside battles. Export a backup in Save & settings to move devices.</p></div>`);}
 function updateOnlineStatus(){
   const {client,players}=EWOnline.status(),node=$('network-state');if(!node)return;
   node.className='offline';node.innerHTML=client?`<i></i> ${client.connected?'ROOM '+client.room:'RECONNECTING'} · ${players.length}`:'<i></i> SOLO';
 }
 function onlineMenu(){
   const {client,players,messages}=EWOnline.status();
   if(!client){
     openModal('Online adventure',`<div class="online-grid"><section class="online-card"><h3>Create a room</h3><p class="modal-copy">Make a private room code and share it with friends. Up to 20 players can explore together.</p><form id="create-room" class="online-form"><label>YOUR RANGER NAME</label><input id="online-name" maxlength="16" required placeholder="Ranger name" value="${EWOnline.esc(localStorage.getItem('emberwild-name')||'')}"><button class="primary">Create room</button></form></section><section class="online-card"><h3>Join friends</h3><p class="modal-copy">Enter the room code shown on your friend’s screen.</p><form id="join-room" class="online-form"><label>ROOM CODE</label><input id="room-code" maxlength="8" required placeholder="ABCDE" autocomplete="off"><label>YOUR RANGER NAME</label><input id="join-name" maxlength="16" required placeholder="Ranger name" value="${EWOnline.esc(localStorage.getItem('emberwild-name')||'')}"><button class="primary">Join room</button></form></section></div><p id="online-error" class="warning" role="status"></p><p class="modal-copy">Online play works when this game is hosted as a web service. Everyone uses the same game link; progress and battles still save separately on each device.</p>`,'online');
     const connect=async(room,n)=>{const err=$('online-error');err.textContent='Connecting…';try{localStorage.setItem('emberwild-name',n);const code=await EWOnline.join(room,n,state);tone(740);say(`Connected to online room ${code}. You can now see other rangers in the world.`);onlineMenu();}catch(e){err.textContent=e.message;}};
     $('create-room').onsubmit=e=>{e.preventDefault();connect('',$('online-name').value);};$('join-room').onsubmit=e=>{e.preventDefault();connect($('room-code').value,$('join-name').value);};return;
   }
   const raid=client.raid||{hp:240,maxHp:240,won:false};
   openModal('Online room',`<div class="online-grid"><section class="online-card"><span class="connection-pill ${client.connected?'good':'bad'}">● ${client.connected?'CONNECTED':'RECONNECTING'}</span><h3>Room code</h3><p class="room-code">${EWOnline.esc(client.room)}</p><button id="copy-room">Copy invite</button><div class="players-list">${players.map(p=>`<div class="online-player"><i style="background:${p.color}"></i><strong>${EWOnline.esc(p.name)}</strong><small>${D.areas[p.area]?.name||'Vale'}${p.id===client.id?' · you':''}</small></div>`).join('')}</div><button id="leave-room">Leave room</button></section><section class="online-card"><h3>Campfire chat</h3><div class="chat-log" id="chat-log">${messages.length?messages.map(m=>`<p class="chat-message ${m.system?'system':''}">${m.system?'✦ ':`<strong>${EWOnline.esc(m.name)}:</strong> `}${EWOnline.esc(m.text)}</p>`).join(''):'<p class="chat-message system">No messages yet. Say hello.</p>'}</div><form id="chat-form" class="chat-form"><input id="chat-text" maxlength="140" placeholder="Message the room" autocomplete="off"><button class="primary">Send</button></form><div class="raid-box"><strong>${raid.won?'Rift Wyrm defeated!':'Co-op Rift Wyrm'}</strong><div class="hp-track"><span style="width:${100*raid.hp/raid.maxHp}%"></span></div><p>${raid.hp} / ${raid.maxHp} shared HP · Two connected players required.</p><button id="raid-hit" ${raid.won?'disabled':''}>Command your companion</button></div></section></div><p id="online-error" class="warning" role="status"></p>`,'online');
   $('copy-room').onclick=async()=>{const invite=`Join my Emberwild room ${client.room}: ${location.href}`;try{await navigator.clipboard.writeText(invite);$('copy-room').textContent='Invite copied!';}catch{$('copy-room').textContent='Code: '+client.room;}};
   $('leave-room').onclick=()=>{EWOnline.leave();modal.close();say('You left the online room. Your solo adventure is still saved.');};
   $('chat-form').onsubmit=async e=>{e.preventDefault();const input=$('chat-text'),text=input.value.trim();if(!text)return;input.value='';try{await EWOnline.chat(text);}catch(err){$('online-error').textContent=err.message;}};
   $('raid-hit').onclick=async()=>{try{const d=await EWOnline.raid();tone(d.won?880:330);$('online-error').textContent=d.won?'Your room restored the rift beacon together!':`Your companion dealt ${d.damage} shared damage.`;}catch(err){$('online-error').textContent=err.message;}};
   const log=$('chat-log');log.scrollTop=log.scrollHeight;
 }
 function gameMenu(){
   openModal('Pause menu',`<p class="eyebrow">${state?D.areas[state.area].name.toUpperCase():'THE VALE'} · ${EWOnline.status().client?'ONLINE ROOM '+EWOnline.status().client.room:'SOLO ADVENTURE'}</p><div class="pause-menu"><button id="resume-menu" class="primary">Resume adventure</button><button id="pause-party" ${!state?'disabled':''}>Party</button><button id="pause-quests" ${!state?'disabled':''}>Quest log</button><button id="pause-inventory" ${!state?'disabled':''}>Inventory</button><button id="pause-journal" ${!state?'disabled':''}>Field journal</button><button id="pause-online">Online room</button><button id="pause-settings">Save & settings</button><button id="pause-guide">Ranger’s guide</button><button id="return-title">Return to title</button></div>`,'pause');
   $('resume-menu').onclick=()=>modal.close();$('pause-party').onclick=team;$('pause-quests').onclick=questLog;$('pause-inventory').onclick=inventory;$('pause-journal').onclick=journal;$('pause-online').onclick=onlineMenu;$('pause-settings').onclick=settings;$('pause-guide').onclick=help;$('return-title').onclick=()=>{modal.close();document.body.classList.remove('game-active');$('title-screen').classList.remove('closed');};
 }
 function downloadSave(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='emberwild-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function settings(){
   if(battle){say('Finish this battle and press Continue adventure before managing saves.');return;}
   openModal('Save & settings',`<p class="modal-copy">${storageOK?'Progress stays in this browser on this device.':'Browser storage is unavailable. Export a backup to keep progress.'} Download a backup before clearing browser data or moving devices.</p><div class="modal-buttons"><button id="export" class="primary" ${!state?'disabled':''}>Export save</button><button id="new-game">Start a new journey</button></div><p class="modal-copy">Restore a backup (.json). Your current journey will be replaced only after confirmation.</p><input class="file-input" type="file" id="import" accept=".json,application/json"><p id="import-status" class="warning" role="status"></p><p class="modal-copy">Emberwild v3.0 · Hollowroot adventure, quest log, inventory and tactical abilities.<br>All art, music and sound are generated by the included code. Solo play works offline; online rooms require the Node server.</p>`,'settings');
   $('export').onclick=downloadSave;$('new-game').onclick=()=>{openModal('Begin again?',`<p class="modal-copy">This replaces your current journey. Export a backup first if you want to keep it.</p><div class="modal-buttons"><button id="reset">Replace save & restart</button><button id="cancel-reset" class="primary">Keep exploring</button></div>`);$('cancel-reset').onclick=()=>modal.close();$('reset').onclick=()=>{try{localStorage.removeItem(D.SAVE_KEY);}catch{}state=null;battle=null;modal.close();welcome();say('A fresh journey awaits. Choose your companion.');};};
   $('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>100000)throw Error('Save file is too large.');const loaded=C.validate(JSON.parse(await f.text()));openModal('Restore this journey?',`<p class="modal-copy">${D.areas[loaded.area].name} · ${loaded.team.length} companions · ${loaded.badges.length} crests. This will replace your current progress.</p><div class="modal-buttons"><button id="restore" class="primary">Restore save</button><button id="cancel-import">Cancel</button></div>`);$('cancel-import').onclick=settings;$('restore').onclick=()=>{state=loaded;$('overlay').hidden=true;modal.close();renderHUD();save();say('Your journey has been restored. Welcome back.');};}catch(err){$('import-status').textContent='Could not import: '+err.message;}};
 }
 $('save').onclick=()=>battle?say('Your last checkpoint is before this battle. Finish the encounter to save.'):save(true);
 $('help').onclick=help;$('journal').onclick=journal;$('team-button').onclick=team;$('settings').onclick=settings;$('interact').onclick=interact;
 $('online').onclick=onlineMenu;$('game-menu').onclick=gameMenu;$('dock-team').onclick=team;$('dock-journal').onclick=journal;$('dock-online').onclick=onlineMenu;$('dock-save').onclick=()=>save(true);
 $('sound').onclick=()=>{setSound(muted);tone(660);};$('title-sound').onclick=()=>{setSound(muted);tone(660);};
 $('fullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch{say('Full-screen mode is not available in this browser.');}};
 const dirs={ArrowUp:[0,-1,'up'],w:[0,-1,'up'],ArrowDown:[0,1,'down'],s:[0,1,'down'],ArrowLeft:[-1,0,'left'],a:[-1,0,'left'],ArrowRight:[1,0,'right'],d:[1,0,'right']};
 window.addEventListener('keydown',e=>{if(modal.open||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;const key=e.key.length===1?e.key.toLowerCase():e.key;if(dirs[key]){e.preventDefault();const now=performance.now();if(now-lastMove>110){move(...dirs[key]);lastMove=now;}}else if((key==='e'||(key===' '&&document.activeElement.tagName!=='BUTTON'))){e.preventDefault();interact();}else if(key==='j')journal();else if(key==='t')team();else if(key==='Escape')gameMenu();});
 let touchTimer=null;function stopTouch(){clearInterval(touchTimer);touchTimer=null;}
 document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();stopTouch();b.setPointerCapture(e.pointerId);const dir=Object.values(dirs).find(v=>v[2]===b.dataset.move);move(...dir);touchTimer=setInterval(()=>move(...dir),160);};b.onpointerup=stopTouch;b.onpointercancel=stopTouch;b.onlostpointercapture=stopTouch;});window.addEventListener('blur',stopTouch);
 document.addEventListener('visibilitychange',()=>{if(document.hidden){stopTouch();save();}});
 function frame(t){A.world(ctx,state,t);EWOnline.draw(ctx);requestAnimationFrame(frame);}requestAnimationFrame(frame);
 try{const raw=localStorage.getItem(D.SAVE_KEY);if(raw)state=C.validate(JSON.parse(raw));}catch{storageOK=false;say('The saved journey could not be loaded. You can import a backup in Save & settings.');}
 try{muted=localStorage.getItem('emberwild-sound')!=='on';}catch{}setSound(!muted);
 EWOnline.subscribe(()=>{updateOnlineStatus();if(modal.open&&modalKind==='online'&&EWOnline.status().client)onlineMenu();});
 if(state){renderHUD();say(`Welcome back to ${D.areas[state.area].name}. Your companions are ready.`);EWOnline.resume(state);}else welcome();
 $('continue-game').disabled=!state;$('continue-game').textContent=state?'Continue adventure':'No saved adventure';
 $('continue-game').onclick=enterGame;
 $('new-title-game').onclick=()=>{enterGame();if(!state){welcome();return;}openModal('Begin a new adventure?',`<p class="modal-copy">This replaces your current local journey. Export a backup from Save & settings if you want to keep it.</p><div class="modal-buttons"><button id="title-reset">Begin again</button><button id="title-cancel" class="primary">Keep current save</button></div>`);$('title-cancel').onclick=()=>modal.close();$('title-reset').onclick=()=>{EWOnline.leave();try{localStorage.removeItem(D.SAVE_KEY);}catch{}state=null;battle=null;modal.close();welcome();};};
 $('online-title').onclick=()=>{enterGame();onlineMenu();};
})();


